Cargo.lock
Cargo.toml

ui-v0.0.67.zip published at https://github.com/restatedev/restate-web-ui/releases/download/v0.0.67/ui-v0.0.67.zip
sha256: 3800458fd611ac87ba2ada9a782cb6bb2331b5460b4fd043740719a8d4fb7b60

[Restate UI] Update to v0.0.67

---

Cargo.lock
Cargo.toml

ui-v0.0.68.zip published at https://github.com/restatedev/restate-web-ui/releases/download/v0.0.68/ui-v0.0.68.zip
sha256: eb4c6503c5395b7cbfc60b5901f83fa257968fdd0f2396ea3b00489534732745

[Restate UI] Update to v0.0.68

---

Cargo.lock
Cargo.toml

ui-v0.0.69.zip published at https://github.com/restatedev/restate-web-ui/releases/download/v0.0.69/ui-v0.0.69.zip
sha256: 9558464678beb35e9b93a92b6b7532859c8c30c136441ba72c6010a6179b237d

[Restate UI] Update to v0.0.69

---

Cargo.lock
Cargo.toml

ui-v0.0.70.zip published at https://github.com/restatedev/restate-web-ui/releases/download/v0.0.70/ui-v0.0.70.zip
sha256: dae47718fabaaf2230befa36aabac051ee9d804330a841e92bb1c5a5c083f84f

[Restate UI] Update to v0.0.70

---

Cargo.lock
Cargo.toml

ui-v0.0.71.zip published at https://github.com/restatedev/restate-web-ui/releases/download/v0.0.71/ui-v0.0.71.zip
sha256: e644d8f0d1ba64803001f94438e9676bd686979dabc05e7903474f230823d974

[Restate UI] Update to v0.0.71

---

Cargo.lock
Cargo.toml

ui-v0.0.72.zip published at https://github.com/restatedev/restate-web-ui/releases/download/v0.0.72/ui-v0.0.72.zip
sha256: 69d1ee3ce397d71fb3b9bae4494c8e6273568e0b2991cc9b79be87d3761390e5

[Restate UI] Update to v0.0.72

---

Cargo.lock
Cargo.toml

ui-v0.0.73.zip published at https://github.com/restatedev/restate-web-ui/releases/download/v0.0.73/ui-v0.0.73.zip
sha256: 03cc3deeda3b9648abc108c8cf80484153625c08658781e8e8fec180896e5b4e

[Restate UI] Update to v0.0.73

---

Cargo.lock
Cargo.toml

ui-v0.0.74.zip published at https://github.com/restatedev/restate-web-ui/releases/download/v0.0.74/ui-v0.0.74.zip
sha256: bffbb28024b899bb6da5df80ebf9a2ebfd64403ff9503c1edbb29900439bbf47

[Restate UI] Update to v0.0.74

---

Cargo.lock
Cargo.toml

ui-v0.0.75.zip published at https://github.com/restatedev/restate-web-ui/releases/download/v0.0.75/ui-v0.0.75.zip
sha256: 02ca41a8e8e966ede55c336954509e95e8ce5da2ee1d666eb4929f39bdf233e8

[Restate UI] Update to v0.0.75

---

Cargo.lock
Cargo.toml

ui-v0.0.76.zip published at https://github.com/restatedev/restate-web-ui/releases/download/v0.0.76/ui-v0.0.76.zip
sha256: 442cb097c378735e970b35ee2d05c71f1456d7675fb82febefbb4c85f045f77e

[Restate UI] Update to v0.0.76

---

Cargo.lock
Cargo.toml

ui-v0.0.77.zip published at https://github.com/restatedev/restate-web-ui/releases/download/v0.0.77/ui-v0.0.77.zip
sha256: fd6d4d131d23b343eb71cca729a2d586e370e55683b39c58579d8489d3b22ac3

[Restate UI] Update to v0.0.77

---

Cargo.lock
Cargo.toml

ui-v0.0.78.zip published at https://github.com/restatedev/restate-web-ui/releases/download/v0.0.78/ui-v0.0.78.zip
sha256: 59fbad9a8215afdd95f9ea633fdbc59d7a12a7bc866de77a731c5176a0a69a05

[Restate UI] Update to v0.0.78

---

Cargo.lock
Cargo.toml

ui-v0.0.80.zip published at https://github.com/restatedev/restate-web-ui/releases/download/v0.0.80/ui-v0.0.80.zip
sha256: df211030ae6af4d464fdf880741d8192f26926648a2ae84d290d57e7377c198c

[Restate UI] Update to v0.0.80

---

Cargo.lock
Cargo.toml

ui-v0.0.81.zip published at https://github.com/restatedev/restate-web-ui/releases/download/v0.0.81/ui-v0.0.81.zip
sha256: a9564916e910cd418ecba382c849e550ad8b522dd1cf6d4d3eef537aec7e265e

[Restate UI] Update to v0.0.81

---

Cargo.lock
Cargo.toml

ui-v0.0.82.zip published at https://github.com/restatedev/restate-web-ui/releases/download/v0.0.82/ui-v0.0.82.zip
sha256: f74d60a3bbd1f39dd14ae245e19d78fc0e7e5843f0f9a9d61bbb54baed01bc8c

[Restate UI] Update to v0.0.82

---

Cargo.lock
Cargo.toml

ui-v0.0.83.zip published at https://github.com/restatedev/restate-web-ui/releases/download/v0.0.83/ui-v0.0.83.zip
sha256: 7b4897da679d497062864844a3c7586de9e07724dd43073dcae77566a0a09a88

[Restate UI] Update to v0.0.83

---

Cargo.lock
Cargo.toml

ui-v0.0.85.zip published at https://github.com/restatedev/restate-web-ui/releases/download/v0.0.85/ui-v0.0.85.zip
sha256: 062741836cc71b021dbf3496d051624a72b1ac3822dad417c735750ef5f42a47

[Restate UI] Update to v0.0.85

---

Cargo.lock
Cargo.toml

ui-v0.0.86.zip published at https://github.com/restatedev/restate-web-ui/releases/download/v0.0.86/ui-v0.0.86.zip
sha256: 8a1c7a6d48adaa20f89c11888704d410c3c8e67cad0e74fb06436cf77d98d70a

[Restate UI] Update to v0.0.86

---

Cargo.lock
Cargo.toml

ui-v0.0.89.zip published at https://github.com/restatedev/restate-web-ui/releases/download/v0.0.89/ui-v0.0.89.zip
sha256: 0138f7259ce75ad27f1faa532add43dbb261fb1bf4d3b5e0edbfb7f79f404fe8

[Restate UI] Update to v0.0.89

---

Cargo.lock
Cargo.toml

ui-v0.0.90.zip published at https://github.com/restatedev/restate-web-ui/releases/download/v0.0.90/ui-v0.0.90.zip
sha256: 30837bb4bc9b76ed86ba957a175b4fd61543597b9f4f716b3003e25e5df6bd5a

[Restate UI] Update to v0.0.90

---

Cargo.lock
Cargo.toml

ui-v0.0.92.zip published at https://github.com/restatedev/restate-web-ui/releases/download/v0.0.92/ui-v0.0.92.zip
sha256: 13dee3dcd8586b8fdc905e0aa0801e97819bed0f8e693ae70f400bab3d632e1e

[Restate UI] Update to v0.0.92

---

Cargo.lock
Cargo.toml

ui-v0.0.93.zip published at https://github.com/restatedev/restate-web-ui/releases/download/v0.0.93/ui-v0.0.93.zip
sha256: 4a1cc9a00fddc85aecdef3a756179646ea7a1fadce89ad393f4417c982eeb5f6

[Restate UI] Update to v0.0.93

---

Cargo.lock
Cargo.toml

ui-v0.0.94.zip published at https://github.com/restatedev/restate-web-ui/releases/download/v0.0.94/ui-v0.0.94.zip
sha256: 958befaaf90f48d9850cbdb411ae0e62e1a531bdfd14f1ed6fff592184a3f199

[Restate UI] Update to v0.0.94

---

Cargo.lock
Cargo.toml

ui-v0.0.96.zip published at https://github.com/restatedev/restate-web-ui/releases/download/v0.0.96/ui-v0.0.96.zip
sha256: a368c46f1094249a8722c857b2110822fcc3c0bc484e651d421d72dfbb64babe

[Restate UI] Update to v0.0.96

---

Cargo.lock
Cargo.toml

ui-v0.0.97.zip published at https://github.com/restatedev/restate-web-ui/releases/download/v0.0.97/ui-v0.0.97.zip
sha256: d69416471e1192ceb900c06941a197e78d858dff6ef65136d8bceb72ca094bce

[Restate UI] Update to v0.0.97

---

Cargo.lock
Cargo.toml

ui-v0.1.2.zip published at https://github.com/restatedev/restate-web-ui/releases/download/v0.1.2/ui-v0.1.2.zip
sha256: 393fe46fd40bd8e0e4e47130824b78f4d4d8ec27b5b338fc8dc4b9564e52caef

[Restate UI] Update to v0.1.2

---

Cargo.lock
Cargo.toml

ui-v0.1.4.zip published at https://github.com/restatedev/restate-web-ui/releases/download/v0.1.4/ui-v0.1.4.zip
sha256: 167b4f86a63e40742ea53a8857b06791a030a860c3f9ee0ee2c30b47047a17fb

[Restate UI] Update to v0.1.4

---

Cargo.lock
Cargo.toml

ui-v0.1.8.zip published at https://github.com/restatedev/restate-web-ui/releases/download/v0.1.8/ui-v0.1.8.zip
sha256: 5ffe8ed0a7151e8eaf6f712d2ee395ecd6adaad0823810349a701169b0263f35

[Restate UI] Update to v0.1.8

---

Cargo.lock
Cargo.toml

ui-v0.1.11.zip published at https://github.com/restatedev/restate-web-ui/releases/download/v0.1.11/ui-v0.1.11.zip
sha256: 616e9f6cdbf0618347d23b176daf3cb1a7b648d44ff91f8f1e3510e2332538dd

[Restate UI] Update to v0.1.11
